[StereoKitC]
git-tree-sha1 = "93907d367040a2a10fbd6c9d4f35fbaf55dce78d"

    [[StereoKitC.download]]
    url = "https://raw.githubusercontent.com/IanET/LibStereoKitGenerator/StereoKit-0.3.5/StereoKitC/runtimes/win10-x64.tar.gz"
    sha256 = "db451e1080f52527ef9931e5c1dc3256ce52d07837590c44fb8118db981eaabd"
