[StereoKitC]
git-tree-sha1 = "4bec1fd7d77aef892fbae4271117f7e6bf50cf53"

    [[StereoKitC.download]]
    url = "https://raw.githubusercontent.com/IanET/LibStereoKitGenerator/v0.3.6/StereoKitC/runtimes/win-x64.tar.gz"
    sha256 = "0fa5ca216ebbd36519a05da7e08e6d3453d49073472cdc5a94e72b88dbf126c6"
